# Generated by Django 6.0 on 2026-01-14 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scheduling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Início Previsto')),
                ('end_time', models.DateTimeField(verbose_name='Fim Previsto')),
                ('real_start_time', models.DateTimeField(blank=True, null=True, verbose_name='Início Real')),
                ('real_end_time', models.DateTimeField(blank=True, null=True, verbose_name='Fim Real')),
                ('status', models.CharField(choices=[('PEND', 'Pendente/Agendado'), ('CONF', 'Confirmado'), ('EXEC', 'Em Execução'), ('CONC', 'Concluído'), ('CANC', 'Cancelado')], default='PEND', max_length=4, verbose_name='Status')),
                ('purpose', models.CharField(max_length=200, verbose_name='Finalidade/Projeto')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedulings', to='equipments.equipment', verbose_name='Equipamento')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedulings', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante')),
            ],
            options={
                'verbose_name': 'Agendamento',
                'verbose_name_plural': 'Agendamentos',
                'ordering': ['start_time'],
            },
        ),
    ]
