# Generated by Django 6.0 on 2026-01-15 20:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Insumo')),
                ('unit', models.CharField(max_length=20, verbose_name='Unidade (ex: mL, g, un)')),
                ('current_stock', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Estoque Atual')),
                ('cost_per_unit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Custo Unitário (R$)')),
            ],
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título da Análise')),
                ('description', models.TextField(blank=True, verbose_name='Descrição / Metodologia')),
                ('project_name', models.CharField(blank=True, max_length=150, verbose_name='Projeto de Pesquisa')),
                ('status', models.CharField(choices=[('planned', 'Planejada'), ('ongoing', 'Em Andamento'), ('approved', 'Aprovada / Concluída'), ('rejected', 'Rejeitada / Cancelada')], default='planned', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('researcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to=settings.AUTH_USER_MODEL, verbose_name='Pesquisador Responsável')),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Início')),
                ('end_time', models.DateTimeField(verbose_name='Fim')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='laboratory.analysis')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='equipments.equipment')),
            ],
            options={
                'verbose_name': 'Reserva de Equipamento',
                'verbose_name_plural': 'Reservas de Equipamentos',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='MaterialUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_used', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantidade Usada')),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials_used', to='laboratory.analysis')),
                ('consumable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='laboratory.consumable')),
            ],
        ),
    ]
