# Generated by Django 6.0 on 2026-01-19 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumable',
            name='cost_per_unit',
        ),
        migrations.RemoveField(
            model_name='consumable',
            name='current_stock',
        ),
        migrations.AddField(
            model_name='consumable',
            name='expiration_date',
            field=models.DateField(blank=True, null=True, verbose_name='Validade'),
        ),
        migrations.AddField(
            model_name='consumable',
            name='minimum_stock',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=10, verbose_name='Estoque Mínimo'),
        ),
        migrations.AddField(
            model_name='consumable',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Quantidade Atual'),
        ),
        migrations.AlterField(
            model_name='consumable',
            name='unit',
            field=models.CharField(help_text='Ex: mL, g, frascos, caixas', max_length=20, verbose_name='Unidade'),
        ),
    ]
