# Generated by Django 6.0 on 2026-01-19 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0002_remove_consumable_cost_per_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumable',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo?'),
        ),
    ]
