# Generated by Django 6.0 on 2026-01-14 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Equipamento')),
                ('asset_tag', models.CharField(max_length=50, unique=True, verbose_name='Patrimônio/Tag')),
                ('brand', models.CharField(blank=True, max_length=100, null=True, verbose_name='Marca')),
                ('model', models.CharField(blank=True, max_length=100, null=True, verbose_name='Modelo')),
                ('analysis_time_minutes', models.PositiveIntegerField(default=60, help_text='Tempo estimado para uma análise completa neste equipamento.', verbose_name='Tempo Médio por Análise (min)')),
                ('cost_per_hour', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Custo por Hora (R$)')),
                ('status', models.CharField(choices=[('DISP', 'Disponível'), ('OCUP', 'Ocupado/Em Uso'), ('MAN', 'Em Manutenção'), ('QUE', 'Quebrado/Inutilizável')], default='DISP', max_length=4, verbose_name='Status Atual')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='equipments/', verbose_name='Foto')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Cadastrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Equipamento',
                'verbose_name_plural': 'Equipamentos',
                'ordering': ['name'],
            },
        ),
    ]
