# Generated by Django 6.0 on 2026-01-19 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='status',
            field=models.CharField(choices=[('DISP', 'Disponível'), ('OCUP', 'Ocupado/Em Uso'), ('MAN', 'Em Manutenção'), ('QUE', 'Quebrado/Inutilizável'), ('DES', 'Desativado/Arquivado')], default='DISP', max_length=4, verbose_name='Status Atual'),
        ),
    ]
