# Generated by Django 6.0 on 2026-02-26 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0002_alter_equipment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='category',
            field=models.CharField(default='Geral', help_text='Ex: Cromatografia, Espectroscopia, Preparo...', max_length=50, verbose_name='Setor/Categoria'),
        ),
    ]
